### ISSUE TITLE
Path isn't set correctly(?)

### ISSUE THREAD

**Issue by CatboyCoding** [rosenbjerg/Red#17]
Alright so the code i use to get the path is
```cs
path = Path.GetFullPath(Path.Combine(API.Helper.getModDirectory(this), "..", "..", "..", "htdocs")+"/");
```
(equal to `C:\Users\[censored]\OneDrive\Skrivbord\goose\htdocs\`)
but when Red loads it says `Content root path: C:\Users\[censored]\OneDrive\Skrivbord\goose\`
help?

**Comment by rosenbjerg** [comment]
`Content root path` will always be the working directory the server was started from.
For instance, I started it from my IDE and got this Content root path:
C:\Users\myuser\Documents\GitHub\Test\Test\bin\Debug\netcoreapp3.1\
After creating a test project to have a look at your issues.

If I create a folder named `htdocs` inside the `netcoreapp3.1` folder, and put an index.html file inside that, it is served by the code snippet you have provided.

I'll recommended using a relative path for the static file directory, as I find that easier.
So I'll close this issue, hoping that my explanation has helped you understand the problem. Otherwise, feel free to reopen and post more details.

**Comment by rosenbjerg** [comment]
`Content root path` is not the path that Red serves static files from. `Content root path` is the current working directory of the server, which is only really relevant if you use relative paths for static files folder and so on
