### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by sensboston** [rosenbjerg/Red#2]
Your server always fails on Windows 10, on **_listener.Start();** in _RedHttpServer.cs_ on Windows 10 with exception System.Net.HttpListenerException: 'Access is denied'

I just curious: have you ever tested your code before publishing?

**Comment by rosenbjerg** [comment]
I have been quite busy with education and haven't been very active on this project for some time, so my reply now is likely meaningless. Your problem is that the server needs admin rights on Windows 10 to listen to the wildcard '*', which it will try to. 
I've decided to stop maintaining the .NET Framework version and focus on the .NET Core version, and since this problem is related to the .NET Framework version, I will be closing this ticket. I hope you solved this long ago, and sorry for the (very) late reply.
